In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data =pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [36]:
one_hot_encoder=OneHotEncoder()
geo_encoder=one_hot_encoder.fit(data[['Geography']])
geo_data=geo_encoder.transform(data[['Geography']])
print(one_hot_encoder.get_feature_names_out())
print(geo_data.shape)

['Geography_France' 'Geography_Germany' 'Geography_Spain']
(10000, 3)

In [37]:
geo_encoder_df=pd.DataFrame(geo_data.toarray(),columns=['France','Germany','Spain'])

In [38]:
geo_encoder_df

      France  Germany  Spain
0        1.0      0.0    0.0
1        0.0      0.0    1.0
2        1.0      0.0    0.0
3        1.0      0.0    0.0
4        0.0      0.0    1.0
...      ...      ...    ...
9995     1.0      0.0    0.0
9996     1.0      0.0    0.0
9997     1.0      0.0    0.0
9998     0.0      1.0    0.0
9999     1.0      0.0    0.0

[10000 rows x 3 columns]

In [39]:
x=pd.concat([data.drop(['Exited','Geography'],axis=1),geo_encoder_df],axis=1)
y=data['Exited']
print(x.shape,y.shape)

(10000, 12) (10000,)

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,France,Germany,Spain
9254,686,1,32,6,0.00,2,1,1,179093.26,1.0,0.0,0.0
1561,632,1,42,4,119624.60,2,1,1,195978.86,0.0,1.0,0.0
1670,559,1,24,3,114739.92,1,1,0,85891.02,0.0,0.0,1.0
6087,561,0,27,9,135637.00,1,1,0,153080.40,1.0,0.0,0.0
6669,517,1,56,9,142147.32,1,0,0,39488.04,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,768,1,54,8,69712.74,1,1,1,69381.05,1.0,0.0,0.0
5191,682,0,58,1,0.00,1,1,1,706.50,1.0,0.0,0.0
5390,735,0,38,1,0.00,3,0,0,92220.12,1.0,0.0,0.0
860,667,1,43,8,190227.46,1,1,0,97508.04,1.0,0.0,0.0
7270,697,1,51,1,147910.30,1,1,1,53581.14,0.0,1.0,0.0

In [42]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [43]:
import pickle
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

In [44]:
with open('geo_encoder.pkl','wb') as file:
    pickle.dump(geo_encoder,file)

In [45]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [47]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
import datetime

In [48]:
model=Sequential([
    Dense(32,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(16,activation='relu'),
    Dense(1,activation='sigmoid')
])

c:\Users\HP\OneDrive\Desktop\AI\PYTHON\ANNPROJECT\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 20)             │           260 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │           210 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 481 (1.88 KB)

 Trainable params: 481 (1.88 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [50]:
log_dir="logs/fit"+datetime.datetime.now().strftime("%y%m%d-%H%M%S")

tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

early_stopping_callback=EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [51]:
history=model.fit(
    X_train,y_train,
    validation_data=[X_test,y_test],
    epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7806 - loss: 0.4798 - val_accuracy: 0.8165 - val_loss: 0.4160
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8221 - loss: 0.4148 - val_accuracy: 0.8395 - val_loss: 0.3902
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8422 - loss: 0.3848 - val_accuracy: 0.8475 - val_loss: 0.3641
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8521 - loss: 0.3633 - val_accuracy: 0.8590 - val_loss: 0.3559
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8560 - loss: 0.3525 - val_accuracy: 0.8595 - val_loss: 0.3501
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8583 - loss: 0.3469 - val_accuracy: 0.8600 - val_loss: 0.3474
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8601 - loss: 0.3424 - val_accuracy: 0.8595 - val_loss: 0.3462
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8615 - loss: 0.3397 - val_accuracy: 0.8590 - val_loss: 0.3437
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8605 - loss: 0.3375 - val_accuracy: 0.8565 - val_loss: 0.3472
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3367 - val_accuracy: 0.8615 - val_loss: 0.3427
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8599 - loss: 0.3340 - val_accuracy: 0.8580 - val_loss: 0.3440
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8604 - loss: 0.3331 - val_accuracy: 0.8615 - val_loss: 0.3436
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8619 - loss: 0.3308 - val_accuracy: 0.8605 - val_loss: 0.3429
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8612 - loss: 0.3299 - val_accuracy: 0.8630 - val_loss: 0.3439
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8626 - loss: 0.3286 - val_accuracy: 0.8615 - val_loss: 0.3462
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8633 - loss: 0.3284 - val_accuracy: 0.8610 - val_loss: 0.3462
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3266 - val_accuracy: 0.8620 - val_loss: 0.3422
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8641 - loss: 0.3262 - val_accuracy: 0.8670 - val_loss: 0.3426
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8640 - loss: 0.3250 - val_accuracy: 0.8625 - val_loss: 0.3428
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8639 - loss: 0.3243 - val_accuracy: 0.8650 - val_loss: 0.3422
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8643 - loss: 0.3229 - val_accuracy: 0.8610 - val_loss: 0.3488
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8669 - loss: 0.3219 - val_accuracy: 0.8645 - val_loss: 0.3442
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3210 - val_accuracy: 0.8615 - val_loss: 0.3425
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8651 - loss: 0.3214 - val_accuracy: 0.8650 - val_loss: 0.3426
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8656 - loss: 0.3197 - val_accuracy: 0.8635 - val_loss: 0.3434
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - loss: 0.3197 - val_accuracy: 0.8645 - val_loss: 0.3453
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8656 - loss: 0.3193 - val_accuracy: 0.8625 - val_loss: 0.3438

In [35]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [28]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [30]:
%tensorboard --logdir logs/fit260604-102757/